import { execSync } from 'child_process';
import { copyFileSync, mkdirSync, existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

console.log('🔨 Building SvelteKit project...');
execSync('npm run build', { stdio: 'inherit' });

console.log('📁 Creating Netlify build directory...');
const buildDir = 'build';
if (existsSync(buildDir)) {
  execSync(`rmdir /s /q "${buildDir}"`, { stdio: 'inherit' });
}
mkdirSync(buildDir, { recursive: true });

console.log('📋 Copying client files...');
const clientDir = '.svelte-kit/output/client';
const serverDir = '.svelte-kit/output/server';

// Copy all files from client directory
if (existsSync(clientDir)) {
  execSync(`xcopy "${clientDir}\\*" "${buildDir}\\" /E /I /Y`, { stdio: 'inherit' });
}

// Copy _app directory from server to client
if (existsSync(join(serverDir, '_app'))) {
  execSync(`xcopy "${serverDir}\\_app" "${buildDir}\\_app\\" /E /I /Y`, { stdio: 'inherit' });
}

console.log('🔧 Copying Netlify functions...');
const netlifyDir = '.netlify';
if (existsSync(netlifyDir)) {
  // Copy functions-internal to functions
  if (existsSync(join(netlifyDir, 'functions-internal'))) {
    execSync(`xcopy "${netlifyDir}\\functions-internal" "${buildDir}\\.netlify\\functions\\" /E /I /Y`, { stdio: 'inherit' });
  }
} else {
  console.log('⚠️  No .netlify directory found, functions will be generated by Netlify');
}

console.log('📄 Creating _redirects file...');
// Create _redirects file for SvelteKit SSR
const redirectsContent = `/*    /.netlify/functions/sveltekit-render   200`;
writeFileSync(join(buildDir, '_redirects'), redirectsContent);

console.log('📋 Copying _headers file...');
// Copy _headers file if it exists
if (existsSync('_headers')) {
  copyFileSync('_headers', join(buildDir, '_headers'));
}

console.log('✅ Netlify build completed!');
