const fs = require('fs');
const path = require('path');

const dict = {
  "badges.tier_gold": "Nivel Oro",
  "badges.tier_platinum": "Nivel Platino",
  "badges.tier_legendary": "Nivel Legendario",
  "badges.new_unlocked": "Nueva Insignia Desbloqueada",
  "common.initializing": "Inicializando...",
  "common.achievement": "Logro",
  "admin.msg.impersonate_warning": "Estás personificando a un usuario",
  "common.accept": "Aceptar",
  "nav.donate": "Donar",
  "donate.subtitle": "Apoya nuestro proyecto",
  "donate.badge": "Donación",
  "donate.stripe_btn": "Pagar con Stripe",
  "donate.payment": "Pago",
  "donate.secure": "Pago Seguro",
  "donate.type": "Tipo",
  "legal.privacy.title": "Política de Privacidad",
  "legal.privacy.protocol": "Protocolo",
  "legal.privacy.section1.title": "Sección 1",
  "legal.privacy.section1.desc": "Descripción de la Sección 1",
  "legal.privacy.cards.identity.title": "Identidad",
  "legal.privacy.cards.identity.item1": "Ítem 1",
  "legal.privacy.cards.identity.item2": "Ítem 2",
  "legal.privacy.cards.identity.item3": "Ítem 3",
  "legal.privacy.cards.usage.title": "Uso",
  "legal.privacy.cards.usage.item1": "Ítem 1",
  "legal.privacy.cards.usage.item2": "Ítem 2",
  "legal.privacy.cards.usage.item3": "Ítem 3",
  "legal.privacy.cards.technical.title": "Técnico",
  "legal.privacy.cards.technical.item1": "Ítem 1",
  "legal.privacy.cards.technical.item2": "Ítem 2",
  "legal.privacy.cards.technical.item3": "Ítem 3",
  "legal.privacy.section2.title": "Sección 2",
  "legal.privacy.section2.desc": "Descripción de la Sección 2",
  "legal.privacy.section3.title": "Sección 3",
  "legal.privacy.section3.desc": "Descripción de la Sección 3",
  "legal.privacy.section4.title": "Sección 4",
  "legal.privacy.section4.desc": "Descripción de la Sección 4",
  "legal.privacy.sovereignty.title": "Soberanía de Datos",
  "legal.privacy.sovereignty.desc": "Tus datos son tuyos.",
  "legal.privacy.sovereignty.role": "Rol",
  "legal.privacy.footer": "Pie de página de privacidad",
  "legal.terms.title": "Términos y Condiciones",
  "legal.terms.beta_notice.title": "Aviso de versión Beta",
  "legal.terms.beta_notice.tag": "BETA",
  "legal.terms.beta_notice.desc": "Descripción de versión Beta",
  "legal.terms.updated": "Actualizado",
  "legal.terms.section1.title": "Condición 1",
  "legal.terms.section1.desc": "Detalle de la condición 1",
  "legal.terms.section2.title": "Condición 2",
  "legal.terms.section2.desc": "Detalle de la condición 2",
  "legal.terms.section3.title": "Condición 3",
  "legal.terms.section3.desc": "Detalle de la condición 3",
  "legal.terms.section4.title": "Condición 4",
  "legal.terms.section4.desc": "Detalle de la condición 4",
  "legal.terms.support.title": "Soporte",
  "legal.terms.support.desc": "Contáctanos si necesitas ayuda",
  "legal.terms.support.button": "Contactar Soporte",
  "legal.terms.footer": "Pie de página de términos",
  "classes.edit_title": "Editar Clase",
  "nav.attendance": "Asistencia",
  "common.create": "Crear",
  "common.details": "Detalles",
  "nav.management": "Gestión",
  "nav.premium_features": "Características Premium",
  "nav.payments": "Pagos",
  "nav.skills": "Habilidades",
  "common.processing": "Procesando...",
  "panel.management": "Administración",
  "classes.name_required": "Nombre Requerido",
  "classes.schedule_required": "Horario Requerido",
  "classes.create_success": "Clase Creada Exitosamente",
  "classes.new_title": "Nueva Clase",
  "classes.back_to_list": "Volver a la Lista",
  "classes.new_subtitle": "Crea una nueva clase",
  "classes.create_btn": "Crear Clase",
  "classes.description": "Descripción",
  "classes.description_placeholder": "Escribe una descripción...",
  "classes.guidance_title": "Guía",
  "classes.guidance_clarity_desc": "Proporciona claridad a tus alumnos.",
  "classes.guidance_sync_desc": "Mantén la información sincronizada.",
  "common.back": "Atrás",
  "classes.students_short": "Alumnos",
  "classes.attendance": "Asistencia",
  "classes.configure": "Configurar",
  "classes.overview": "Resumen",
  "classes.syllabus": "Temario",
  "classes.location": "Ubicación",
  "classes.to_be_defined": "Por Definir",
  "classes.period": "Periodo",
  "classes.limit": "Límite",
  "classes.attendance_rate": "Asistencia media",
  "classes.punctuality": "Puntualidad",
  "classes.retention": "Retención",
  "students.enroll_btn": "Inscribir",
  "students.enroll_desc": "Añade un alumno a esta clase.",
  "classes.last_session": "Última sesión",
  "classes.activity_summary": "Resumen de actividad",
  "common.manage": "Gestionar",
  "students.start_adding": "Empieza a añadir alumnos",
  "students.years": "años",
  "common.mixed": "Mixto",
  "students.no_email": "Sin correo",
  "students.no_phone": "Sin teléfono",
  "classes.no_syllabus": "Sin Temario",
  "classes.no_syllabus_desc": "Agrega el contenido de estudio de la clase.",
  "common.difficulty": "Dificultad",
  "attendance.save_success": "Asistencia guardada correctamente",
  "classes.back_to_class": "Volver a la Clase",
  "common.years": "años",
  "classes.update_success": "Clase actualizada correctamente",
  "classes.view_details": "Ver detalles",
  "classes.edit_subtitle": "Modifica la información de la clase",
  "classes.technical_doubts": "Dudas Técnicas",
  "classes.help_link": "Enlace de ayuda",
  "common.success.action": "¡Acción completada con éxito!",
  "common.remove": "Eliminar",
  "classes.max_capacity_reached": "Capacidad máxima alcanzada",
  "students.enroll_success": "Alumno inscrito con éxito",
  "common.error_occurred": "Ha ocurrido un error",
  "students.unenroll_title": "Desinscribir Alumno",
  "students.unenroll_confirm": "¿Seguro que deseas desinscribir a este alumno?",
  "common.unenroll": "Desinscribir",
  "students.unenroll_success": "Alumno desinscrito correctamente",
  "classes.manage_students": "Gestionar Alumnos",
  "classes.capacity_management": "Gestión de Capacidad",
  "classes.enrolled": "Inscritos",
  "classes.available": "Disponibles",
  "classes.capacity": "Capacidad",
  "classes.class_list": "Lista de la Clase",
  "classes.no_enrolled": "No hay alumnos inscritos",
  "classes.start_enrolling_desc": "Añade alumnos para empezar",
  "students.years_short": "años",
  "classes.available_students": "Alumnos Disponibles",
  "classes.capacity_desc": "Define cuántos alumnos permite la clase",
  "classes.no_matches": "No hay resultados",
  "classes.no_matches_desc": "No se encontraron alumnos para tu búsqueda",
  "common.deleted_success": "Eliminado permanentemente",
  "common.error_deleting": "Error eliminando el elemento",
  "lobby.type_placeholder": "Escribe para buscar o añadir...",
  "payments.receipt.payment_method": "Método de Pago",
  "common.school": "Escuela",
  "common.select_option": "Selecciona una opción",
  "payments.concepts.monthly_fee": "Cuota Mensual",
  "payments.concepts.registration": "Matrícula",
  "payments.concepts.tournament": "Torneo",
  "payments.concepts.material": "Material",
  "payments.concepts.other": "Otros",
  "payments.receipt.ref_id": "Ref.",
  "payments.receipt.issued_to": "Emitido a",
  "payments.receipt.issue_date": "Fecha de Emisión",
  "payments.receipt.total_paid": "Total Pagado",
  "payments.receipt.confirmation_text": "Pago confirmado y registrado correctamente",
  "schools.form.name_required": "Nombre Requerido",
  "schools.create_success": "Escuela Creada Correctamente",
  "schools.create_error": "Error Creando Escuela",
  "schools.new_title": "Crear Escuela",
  "schools.back": "Atrás",
  "schools.new_subtitle": "Crea una nueva institución",
  "schools.form.name_label": "Nombre",
  "schools.form.name_placeholder": "Introduce un nombre",
  "schools.form.city_label": "Ciudad",
  "schools.form.city_placeholder": "Introduce la ciudad",
  "schools.guide.title": "Guía",
  "schools.guide.step1": "Rellena la información básica",
  "schools.guide.step2": "Configura las cuotas",
  "schools.guide.step3": "Añade profesores",
  "schools.guide.step4": "Comienza a añadir alumnos",
  "schools.help.title": "Centro de Ayuda",
  "schools.help.text": "Si tienes problemas, consulta nuestra documentación.",
  "schools.help.link": "Leer Documentación",
  "schools.new": "Nueva",
  "schools.create_class": "Crear Grupo",
  "schools.form.city_required": "Ciudad requerida",
  "schools.form.invalid_email": "Email inválido",
  "schools.form.invalid_url": "URL inválida",
  "schools.edit_title": "Editar",
  "schools.edit_subtitle": "Modifica la información de la institución",
  "landing.features.multischool.title": "Gestión Multi-Escuela",
  "schools.form.country_label": "País",
  "schools.form.address_label": "Dirección",
  "schools.form.address_placeholder": "Introduce la dirección",
  "actions.messages.title": "Mensajes",
  "schools.form.phone_label": "Teléfono",
  "schools.form.phone_placeholder": "Introduce el teléfono",
  "schools.form.email_label": "Heredar Email",
  "schools.form.email_placeholder": "ejemplo@institucion.com",
  "schools.form.website_label": "Sitio Web",
  "schools.form.website_placeholder": "https://...",
  "schools.status.title": "Estado",
  "schools.status.last_change": "Último Cambio",
  "schools.status.just_now": "Hace un instante",
  "schools.status.active": "Activa",
  "schools.letterhead.title": "Membrete",
  "schools.letterhead.text": "Este logotipo se usará en recibos y facturas.",
  "schools.critical.title": "Zona Crítica",
  "schools.critical.text": "Estas acciones son destructivas y no pueden deshacerse.",
  "settings.danger_zone_title": "Zona de Peligro",
  "settings.delete_account_title": "Eliminar Cuenta",
  "settings.delete_account_desc": "La cuenta será borrada permanentemente",
  "settings.delete_account_confirm_title": "¿Confirmar Eliminación?",
  "settings.delete_account_confirm_msg": "¿Seguro que quieres perder acceso?",
  "settings.delete_login_required": "Se requiere validación de contraseña",
  "settings.delete_account_btn": "Eliminar Ahora",
  "skills.delete_error": "Error al eliminar la habilidad",
  "skills.import_error": "Error al importar banco de ejercicios",
  "skills.process_error": "Ocurrió un error en el procesado",
  "common.confirm_delete_multiple": "Confirmación de Eliminado",
  "skills.reorder_error": "Error ordenando",
  "common.info": "Información",
  "common.select_all": "Seleccionar Todos",
  "common.selected": "Seleccionados",
  "common.not_selected": "Sin Selección",
  "common.reorder": "Reorganizar",
  "common.save_success": "Datos Guardados Correctamente",
  "skills.save_error": "No se pudo guardar",
  "common.duration": "Duración",
  "common.duration_unit": "m",
  "common.status_active": "Activo",
  "common.status_inactive": "Inactivo",
  "skills.ui.unsaved": "Cambios sin guardar",
  "skills.edit.discard_btn": "Descartar",
  "skills.edit.save_btn": "Guardar Cambios",
  "skills.edit.tips_spec_desc": "Configuración técnica para los ejercicios",
  "skills.edit.discard_title": "Descartar Cambios",
  "skills.edit.discard_msg": "¿Estás seguro de que quieres desechar el trabajo actual?",
  "skills.edit.discard_confirm": "Sí, descartar",
  "skills.edit.discard_cancel": "No, seguir editando",
  "common.schools": "Escuelas",
  "panel.limits.students": "Límite de Alumnos",
  "panel.upgrade": "Mejorar Plan",
  "classes.enroll": "Inscribirse",
  "students.first_name_placeholder": "Ej: Carlos",
  "common.new": "Nuevo",
  "students.no_notes": "Aún no hay notas sobre el alumno.",
  "common.total": "Total",
  "common.sending": "Enviando...",
  "tournaments.status_in_progress": "En Progreso",
  "tournaments.search_placeholder": "Buscar torneo...",
  "tournaments.create_success": "¡Torneo creado correctamente!",
  "tournaments.format_swiss": "Torneo Suizo",
  "tournaments.format_round_robin": "Liga (Round Robin)",
  "tournaments.format_elimination": "Eliminatoria",
  "tournaments.new_title": "Nuevo Torneo",
  "tournaments.new_subtitle": "Crea una nueva partida",
  "tournaments.general_info": "Información General",
  "tournaments.name_label": "Nombre del Torneo",
  "tournaments.name_placeholder": "Nombre",
  "tournaments.desc_label": "Descripción",
  "tournaments.desc_placeholder": "Agrega información...",
  "tournaments.logistics_title": "Configuración y Logística",
  "tournaments.time_control_label": "Ritmo de Juego",
  "tournaments.time_control_placeholder": "Ej: 10 + 5",
  "tournaments.location_label": "Sede / Lugar",
  "tournaments.location_placeholder": "Sede",
  "tournaments.format_label": "Formato",
  "tournaments.capacity_title": "Límites",
  "tournaments.max_players_label": "Límite de Jugadores",
  "tournaments.preview": "Vista Previa",
  "tournaments.untitled": "Sin Título",
  "tournaments.create_player_desc": "Jugadores configurados para empezar la ronda.",
  "tournaments.publish": "Publicar Torneo",
  "common.reference": "Referencia",
  "tournaments.rounds": "Rondas",
  "reports.performance_title": "Rendimiento",
  "tournaments.prizes.total": "Bote total",
  "tournaments.generate_next_round": "Generar Ronda Siguiente",
  "tournaments.reset_tournament": "Reiniciar",
  "tournaments.preview_tournament": "Mostrar",
  "tournaments.spots_lowercase": "cupos",
  "tournaments.edit_warning": "No modifiques si la liga inició",
  "tournaments.delete_permanently_title": "Borrado Definitivo",
  "tournaments.delete_permanently_desc": "La acción no se puede deshacer.",
  "tournaments.delete_now": "Eliminar ahora",
  "tournaments.reset_structure_title": "Reiniciar Rondas",
  "tournaments.reset_structure_desc": "Perderás el progreso de resultados actuales",
  "nav.goPanel": "Ir a Panel"
};

const missingKeys = JSON.parse(fs.readFileSync('missing.json', 'utf8'));

// Fill missing ones not explicitly in dict
for (const key of missingKeys) {
  if (!dict[key]) {
    const parts = key.split('.');
    const lastPart = parts[parts.length - 1];
    dict[key] = lastPart.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  }
}

const modulesDir = path.join(__dirname, 'src', 'lib', 'locales', 'modules');
const fileBases = fs.readdirSync(modulesDir).map(f => f.replace('.ts', ''));
const translationsByModule = {};

// Group keys by module prefix, default to common if module file does not exist
for (const [key, value] of Object.entries(dict)) {
  let moduleName = key.split('.')[0];
  if (!fileBases.includes(moduleName)) {
    moduleName = 'common';
  }
  
  if (!translationsByModule[moduleName]) {
    translationsByModule[moduleName] = {};
  }
  translationsByModule[moduleName][key] = value;
}

// Inject flats keys into `export const es = {`
for (const [mod, keysObj] of Object.entries(translationsByModule)) {
  const filePath = path.join(modulesDir, `${mod}.ts`);
  let content = fs.readFileSync(filePath, 'utf8');

  // We want to add inside `export const es = {`
  const lines = Object.entries(keysObj).map(([k, v]) => `    '${k}': '${v.replace(/'/g, "\\'")}',`);
  
  const injectString = lines.join('\n') + '\n';
  content = content.replace(/(export\s+const\s+es\s*=\s*\{)/, `$1\n${injectString}`);

  fs.writeFileSync(filePath, content);
}

console.log('Successfully injected translations!');
