[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  PUBLIC_FIREBASE_API_KEY = "AIzaSyAVfcGFylUSYSkwEH0dTrCySqu-SwAhHm4"
  PUBLIC_FIREBASE_AUTH_DOMAIN = "chessnet-2505.firebaseapp.com"
  PUBLIC_FIREBASE_PROJECT_ID = "chessnet-2505"
  PUBLIC_FIREBASE_STORAGE_BUCKET = "chessnet-2505.firebasestorage.app"
  PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "668650751820"
  PUBLIC_FIREBASE_APP_ID = "1:668650751820:web:94d658408221c4c11af1e9"
  PUBLIC_FIREBASE_MEASUREMENT_ID = "G-37RZFE1WJQ"

[[headers]]
  for = "/_app/immutable/*"
  [headers.values]
    cache-control = "public, immutable, max-age=31536000"
